### ISSUE TITLE
Bug in display ranks of user

### ISSUE THREAD

**Issue by pathange-s** [sdslabs/beast-frontend#123]
I got my score of 10 points after critica and msquare reached. but still, at the top, it shows my rank to be 10th. Shouldn't the one who solved late be higher in rank ?
![image](https://user-images.githubusercontent.com/76244077/149614441-205e388c-667a-4658-967b-3a89ff56815d.png)
![image](https://user-images.githubusercontent.com/76244077/149614514-ff95f291-87fa-4832-aad9-409c285bada6.png)

**Comment by Bisht13** [comment]
Fixed
