### ISSUE TITLE
Ambiguity on the date and time settings.

### ISSUE THREAD

**Issue by Aviii06** [sdslabs/beast-frontend#65]
While creating a new competition on the date and time settings it says 24hr but asks for AM and PM.
<img width="766" alt="Screenshot 2021-07-25 at 4 12 51 PM" src="https://user-images.githubusercontent.com/45993519/126896373-3ad1988d-c620-4a9b-93e3-0d724cf5c094.png">

**Comment by Bisht13** [comment]
Fixed
